### PR TITLE
Add a check for start and end of document to try to fix false errors

### LINKED ISSUE #20: `load` gives false error when document ends with `...`
In the REPL:
```js
yaml = require('yaml-ast-parser')
result = yaml.load(`---
whatever: true
...`)
result.errors
```
outputs:
```js
[ YAMLException {
    name: 'YAMLException',
    reason: 'can not read an implicit mapping pair; a colon is missed',
    mark: 
     Mark {
       name: null,
       buffer: '---\nwhatever: true\n...\n\u0000',
       position: 19,
       line: 1,
       column: 0 },
    message: 'JS-YAML: can not read an implicit mapping pair; a colon is missed at line 2, column 1' } ]
```

However, the input document is valid and JS-YAML accepts it without error.

This issue becomes particularly pronounced when using `loadAll` to load multiple documents in a single stream, because this issue will occur many times.

### LINKED ISSUE #21: `loadAll` does not correctly recognize document seperators
In the REPL:

```js
yaml = require('yaml-ast-parser')
docs = []
yaml.loadAll(`---
whatever: true
...
---
whatever: false
...`, d => docs.push(d))
docs[0].errors
docs[1].errors
```
Both document's `errors` collections include (errors attributed to #20 omitted):
```js
YAMLException {
  name: 'YAMLException',
  reason: 'end of the stream or a document separator is expected',
  mark: 
    Mark {
      name: null,
      buffer: '---\nwhatever: true\n...\n---\nwhatever: false\n...\n\u0000',
      position: 25,
      line: 2,
      column: 2 },
  message: 'JS-YAML: end of the stream or a document separator is expected at line 3, column 3' }
```

However, document end and new document delimiters are used correctly and JS-YAML has no issues parsing the file.

### PR DESCRIPTION
**Pull request by adamvoss**
A somewhat blind attempt to fix #20 which appears to fix #21 as well.

### CODE REVIEW

**Comment by adamvoss** [comment]
It looks like the one test failure is a changed failure message, so I suppose there is actually a chance that this is an appropriate fix.

**Comment by KonstantinSviridov** [comment]
Hi, Adam!

I've edited the failing test in order to make you PR acceptable.

As I see, both issues are fixed and have tests, so they can be closed.

I'm going to add the `.vscode` folder to `.gitignore` as we always do so for configuration folders of IDEs.

Thanks for your contributions again !

Regards,
Konstantin

**Comment by adamvoss** [comment]
Thanks for merging these and maintaining this library.  I'm looking forward to the next release!

**Comment by KonstantinSviridov** [comment]
Hi, Adam !

The next version (0.0.34) has finally been released.

**Comment by adamvoss** [comment]
Thank you so much for letting me know!

**Pull request merged**
