### PR TITLE
Export the contents of yamlAST instead of duplicating it

### LINKED ISSUE #11: Typings are not complete
It appears the type definitions in the npm package do not match the code corresponding to the package version.

npm shows I have: yaml-ast-parser@**0.0.33**

in the shipped `index.d.ts, I see:
```typescript
export interface YAMLScalar extends YAMLNode {
    value: string;
    doubleQuoted?: boolean;
    plainScalar?: boolean;
}
```

However, this repository at the **0.0.33** tag shows:
```typescript
export interface YAMLScalar extends YAMLNode{
    value:string
    doubleQuoted?:boolean
    singleQuoted?:boolean
    plainScalar?:boolean
    rawValue:string
}
```

### PR DESCRIPTION
**Pull request by adamvoss**
Export the contents of yamlAST instead of duplicating them.  This should fix #11 and help reduce recurrence of such issues.

### CODE REVIEW

**Comment by adamvoss** [comment]
I'm not sure I understand the TypeScript type system well enough to understand the problem here.

Advice would be appreciated.

**Comment by KonstantinSviridov** [comment]
In order to get rid of compilation failures we have to slightly modify the [parser](https://github.com/raml-org/raml-js-parser-2) code before accepting you PR. This will happen in the nearest days.

**Comment by KonstantinSviridov** [comment]
For now the PR is merged into the `develop` branch as it affects buildability of the parser. It will be merged to `master` with the next parser release.

Regards,
Konstantin Sviridov

**Comment by adamvoss** [comment]
Thanks!  I've subscribed to your [github releases feed](https://github.com/mulesoft-labs/yaml-ast-parser/releases.atom) so will hopefully catch when it releases :-)

**Pull request merged**
